// <auto-generated />
using EF7JsonColumns.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF7JsonColumns.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF7JsonColumns.Models.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SuperHeros");
                });

            modelBuilder.Entity("EF7JsonColumns.Models.SuperHero", b =>
                {
                    b.OwnsOne("EF7JsonColumns.Models.HeroDetail", "HeroDetail", b1 =>
                        {
                            b1.Property<int>("SuperHeroId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SuperHeroId");

                            b1.ToTable("SuperHeros");

                            b1.ToJson("HeroDetail");

                            b1.WithOwner()
                                .HasForeignKey("SuperHeroId");
                        });

                    b.Navigation("HeroDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
